
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: ci-build-template
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: /workspace/Dockerfile

steps:
  - name: docker-build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
  #TODO Add additional steps like unit and integration tests