
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: ci-build-template
spec:
  parameters:
  - name: SONARLOGIN
    description: Token to authenticate with SonarQube server
  - name: PROJECTKEY
    description: Project key from SonarQube server
  - name: ORG
    description: Organization name from SonarQube Server
  - name: SOURCES
    description: Path to source code that needs to be analyzed
  - name: IMAGE
    description: The name of the image to push
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: /workspace/Dockerfile

steps:
  - name: static-code-analysis
    image: gcr.io/tmogoserverless/sonar-scanner:latest
    args:
    - -Dsonar.host.url=https://sonarcloud.io
    - -Dsonar.login=${SONARLOGIN}
    - -Dsonar.projectKey=${PROJECTKEY}
    - -Dsonar.organization=${ORG}
    - -Dsonar.sources=${SOURCES}
  - name: docker-build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
  #TODO Add additional steps like unit and integration tests